#!/usr/bin/env node
// Copies the documentation of the two RESAAS libraries into this site.
//
// The libraries' own docs folders are the source of truth - never edit the copies
// under ../content/django-resaas or ../content/quasar-resaas by hand: change the docs
// in the library, then run this again and commit the result.
//
//   node src/sites/resaas/scripts/sync-docs.mjs
//
// Library locations (defaults: the checkouts on the RESAAS server):
//   DJANGO_RESAAS_DIR=/var/www/lib/django_resaas
//   QUASAR_RESAAS_DIR=/var/www/lib/quasar_resaas
import { execSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const content = join(here, '..', 'content')

const django = process.env.DJANGO_RESAAS_DIR || '/var/www/lib/django_resaas'
const quasar = process.env.QUASAR_RESAAS_DIR || '/var/www/lib/quasar_resaas'

const sources = [
  {
    product: 'django-resaas',
    repo: django,
    docs: join(django, 'docs'),
    // the runnable example app, linked from the docs index as "Minimal example app"
    extra: [{ from: join(django, 'src', 'dev', 'README.md'), to: 'example-app.md' }]
  },
  {
    product: 'quasar-resaas',
    repo: quasar,
    docs: join(quasar, 'docs', 'quasar-resaas'),
    extra: []
  }
]

function commitOf (repo) {
  try {
    return execSync('git log -1 --format=%h%x20%cs', { cwd: repo }).toString().trim()
  } catch {
    return 'unknown'
  }
}

const manifest = { synced_at: new Date().toISOString(), products: {} }

for (const source of sources) {
  if (!existsSync(source.docs)) {
    console.error(`missing ${source.docs} - set ${source.product === 'django-resaas' ? 'DJANGO' : 'QUASAR'}_RESAAS_DIR`)
    process.exit(1)
  }

  const target = join(content, source.product)
  rmSync(target, { recursive: true, force: true })
  mkdirSync(target, { recursive: true })
  cpSync(source.docs, target, { recursive: true, filter: (path) => !path.includes('__pycache__') })

  for (const extra of source.extra) {
    if (existsSync(extra.from)) cpSync(extra.from, join(target, extra.to))
  }

  const [commit, date] = commitOf(source.repo).split(' ')
  manifest.products[source.product] = { commit, date }
  console.log(`${source.product}: ${source.docs} @ ${commit} (${date})`)
}

// a JS module, not .json: this app's i18n Vite plugin cannot transform imported JSON
writeFileSync(join(content, 'manifest.js'), `// generated by scripts/sync-docs.mjs - do not edit\nexport default ${JSON.stringify(manifest, null, 2)}\n`)
console.log('done - commit the updated src/sites/resaas/content/')
