// generated by scripts/sync-docs.mjs - do not edit
export default {
  "synced_at": "2026-09-30T10:30:32.365Z",
  "products": {
    "django-resaas": {
      "commit": "208daa9e",
      "date": "2026-09-28"
    },
    "quasar-resaas": {
      "commit": "ef667aed",
      "date": "2026-09-29"
    }
  }
}
