// generated by scripts/sync-docs.mjs - do not edit
export default {
  "synced_at": "2026-10-03T16:06:43.933Z",
  "products": {
    "django-resaas": {
      "commit": "d51a7c13",
      "date": "2026-10-03"
    },
    "quasar-resaas": {
      "commit": "9b18c30f",
      "date": "2026-10-03"
    }
  }
}
