// generated by scripts/sync-docs.mjs - do not edit
export default {
  "synced_at": "2026-09-28T01:51:16.676Z",
  "products": {
    "django-resaas": {
      "commit": "d7e02283",
      "date": "2026-09-28"
    },
    "quasar-resaas": {
      "commit": "5e17dbd7",
      "date": "2026-09-27"
    }
  }
}
